//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCBZ {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class CBZMageSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CBZMageSettings defaultInstance = ((CBZMageSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CBZMageSettings())));
        
        public static CBZMageSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%APPDATA%\\CBZMage\\temp\\")]
        public string TempFolderPath {
            get {
                return ((string)(this["TempFolderPath"]));
            }
            set {
                this["TempFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5b")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>{title}</string>
  <string>{page}</string>
  <string>{pages}</string>
  <string>{size}</string>
  <string>{number}</string>
  <string>{month}</string>
  <string>{year}</string>
  <string>{lang}</string>
  <string>{series}</string>
  <string>{type}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RenamerPlaceholders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RenamerPlaceholders"]));
            }
        }
    }
}
